# Generated by Django 5.1.15 on 2026-09-09 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('bot_id', models.CharField(max_length=128)),
                ('external_update_id', models.CharField(max_length=128)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'bot_id', 'external_update_id'), name='uniq_provider_bot_update')],
            },
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('external_chat_id', models.CharField(max_length=128)),
                ('state', models.CharField(default='idle', max_length=64)),
                ('pending_action', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_conversations', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'provider', 'external_chat_id'), name='uniq_user_provider_chat_state')],
            },
        ),
        migrations.CreateModel(
            name='CaseMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_status', models.CharField(choices=[('assigned', 'Assigned'), ('unassigned', 'Unassigned')], db_index=True, default='unassigned', max_length=16)),
                ('provider', models.CharField(max_length=32)),
                ('external_chat_id', models.CharField(max_length=128)),
                ('external_message_id', models.CharField(max_length=128)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('audio', 'Audio'), ('image', 'Image'), ('document', 'Document'), ('location', 'Location'), ('unknown', 'Unknown')], max_length=16)),
                ('text', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_messages', to=settings.AUTH_USER_MODEL)),
                ('inbound_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.inboundupdate')),
            ],
            options={
                'ordering': ['sent_at', 'received_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_chat_id', 'external_message_id'), name='uniq_provider_chat_message')],
            },
        ),
    ]
