# Generated by Django 5.1

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("messaging", "0001_initial"),
        ("transcription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_kind", models.CharField(choices=[("message", "Message"), ("transcript_segment", "Transcript segment")], db_index=True, max_length=32)),
                ("text", models.TextField()),
                ("start_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("end_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence_items", to="cases.case")),
                ("message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="evidence_items", to="messaging.casemessage")),
                ("transcript_segment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="evidence_items", to="transcription.transcriptsegment")),
            ],
            options={
                "indexes": [models.Index(fields=["case", "source_kind"], name="evidence_case_source_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(("message__isnull", False), ("source_kind", "message"), ("transcript_segment__isnull", True))
                            | models.Q(("message__isnull", True), ("source_kind", "transcript_segment"), ("transcript_segment__isnull", False))
                        ),
                        name="evidence_valid_source",
                    )
                ],
            },
        ),
    ]
