# Generated by Django 5.2 on 2026-09-10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_case_type_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseAction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("action_type", models.CharField(choices=[
                    ("manual", "اقدام دستی"),
                    ("start_analysis", "شروع تحلیل"),
                    ("review_analysis", "بررسی تحلیل"),
                    ("retry_analysis", "بررسی تحلیل ناموفق"),
                    ("generate_report", "تولید گزارش"),
                    ("review_report", "بررسی گزارش"),
                    ("regenerate_report", "بازسازی گزارش"),
                    ("follow_up", "پیگیری پرونده"),
                ], default="manual", max_length=32)),
                ("status", models.CharField(choices=[
                    ("open", "باز"),
                    ("done", "انجام شده"),
                    ("dismissed", "کنار گذاشته شده"),
                ], db_index=True, default="open", max_length=16)),
                ("priority", models.PositiveSmallIntegerField(choices=[
                    (10, "کم"), (20, "عادی"), (30, "مهم"), (40, "فوری")
                ], db_index=True, default=20)),
                ("due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("system_key", models.CharField(blank=True, max_length=96)),
                ("source_event", models.CharField(blank=True, max_length=96)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="cases.case")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_case_actions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-priority", "due_at", "created_at"]},
        ),
        migrations.AddConstraint(
            model_name="caseaction",
            constraint=models.UniqueConstraint(
                condition=~models.Q(system_key=""),
                fields=("case", "system_key"),
                name="uniq_case_system_action",
            ),
        ),
        migrations.AddIndex(
            model_name="caseaction",
            index=models.Index(fields=["status", "due_at", "priority"], name="case_action_queue_idx"),
        ),
    ]
