# Generated by Django 5.2 on 2026-09-10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_case_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reminders_enabled", models.BooleanField(default=True)),
                ("due_action_enabled", models.BooleanField(default=True)),
                ("report_review_enabled", models.BooleanField(default=True)),
                ("stale_case_enabled", models.BooleanField(default=True)),
                ("daily_digest_enabled", models.BooleanField(default=False)),
                ("weekly_digest_enabled", models.BooleanField(default=True)),
                ("quiet_start", models.TimeField(default="22:00")),
                ("quiet_end", models.TimeField(default="08:00")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="reminder_preference", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CaseReminder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("remind_at", models.DateTimeField(db_index=True)),
                ("status", models.CharField(choices=[("pending", "در انتظار"), ("dispatching", "در حال ارسال"), ("sent", "ارسال شده"), ("cancelled", "لغو شده")], db_index=True, default="pending", max_length=16)),
                ("channel", models.CharField(choices=[("bale", "بله")], default="bale", max_length=16)),
                ("dedupe_key", models.CharField(max_length=160, unique=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reminders", to="cases.caseaction")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="case_reminders", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["remind_at", "created_at"]},
        ),
        migrations.AddIndex(
            model_name="casereminder",
            index=models.Index(fields=["status", "remind_at"], name="case_reminder_due_idx"),
        ),
    ]
