# Generated by Django 5.2 on 2026-09-10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_reminders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("manual", "اقدام دستی"),
                    ("start_analysis", "شروع تحلیل"),
                    ("review_analysis", "بررسی تحلیل"),
                    ("retry_analysis", "بررسی تحلیل ناموفق"),
                    ("generate_report", "تولید گزارش"),
                    ("review_report", "بررسی گزارش"),
                    ("regenerate_report", "بازسازی گزارش"),
                    ("follow_up", "پیگیری پرونده"),
                    ("stale_case", "پرونده بدون اقدام"),
                ],
                default="manual",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="DigestDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("digest_type", models.CharField(choices=[("daily", "خلاصه روزانه"), ("weekly", "خلاصه هفتگی")], max_length=16)),
                ("period_key", models.CharField(max_length=32)),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="digest_deliveries", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="digestdelivery",
            constraint=models.UniqueConstraint(fields=("user", "digest_type", "period_key"), name="uniq_user_digest_period"),
        ),
    ]
