# Generated by Django 5.2 on 2026-09-10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_digest_delivery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseActionSuggestion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("rationale", models.TextField(blank=True)),
                ("suggested_due_at", models.DateTimeField(blank=True, null=True)),
                ("source_evidence_ids", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("fingerprint", models.CharField(max_length=64)),
                ("provider", models.CharField(blank=True, max_length=32)),
                ("model_name", models.CharField(blank=True, max_length=128)),
                ("status", models.CharField(choices=[("proposed", "پیشنهاد شده"), ("accepted", "پذیرفته شده"), ("rejected", "رد شده")], db_index=True, default="proposed", max_length=16)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_action", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="source_suggestions", to="cases.caseaction")),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="action_suggestions", to="cases.case")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_action_suggestions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="caseactionsuggestion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name="caseactionsuggestion",
            constraint=models.UniqueConstraint(fields=("case", "fingerprint"), name="uniq_case_action_suggestion_fingerprint"),
        ),
    ]
