# Generated by Django 5.1

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(choices=[("docx", "DOCX")], default="docx", max_length=16)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("rendering", "Rendering"), ("ready", "Ready"), ("failed", "Failed")], db_index=True, default="pending", max_length=16)),
                ("storage_key", models.CharField(blank=True, max_length=512)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("mime_type", models.CharField(default="application/vnd.openxmlformats-officedocument.wordprocessingml.document", max_length=128)),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requested_documents", to=settings.AUTH_USER_MODEL)),
                ("revision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="generated_documents", to="reports.reportrevision")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("revision", "kind"), name="uniq_revision_document_kind")],
            },
        ),
    ]
