# Generated by Django 5.1

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("evidence", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vertical",
            fields=[
                ("key", models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubVertical",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("vertical", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sub_verticals", to="intelligence.vertical")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("vertical", "key"), name="uniq_vertical_subvertical_key")],
            },
        ),
        migrations.CreateModel(
            name="FieldSchema",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sub_vertical", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="schemas", to="intelligence.subvertical")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("sub_vertical", "version"), name="uniq_subvertical_schema_version")],
            },
        ),
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.SlugField(max_length=96)),
                ("label", models.CharField(max_length=160)),
                ("value_type", models.CharField(choices=[("text", "Text"), ("integer", "Integer"), ("decimal", "Decimal"), ("boolean", "Boolean"), ("date", "Date"), ("datetime", "Datetime"), ("choice", "Choice"), ("json", "JSON")], default="text", max_length=16)),
                ("required", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("choices", models.JSONField(blank=True, default=list)),
                ("extraction_hints", models.JSONField(blank=True, default=dict)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("schema", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fields", to="intelligence.fieldschema")),
            ],
            options={
                "ordering": ["sequence", "key"],
                "constraints": [models.UniqueConstraint(fields=("schema", "key"), name="uniq_schema_field_key")],
            },
        ),
        migrations.CreateModel(
            name="ExtractionRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(max_length=64)),
                ("model_name", models.CharField(blank=True, max_length=128)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("completed", "Completed"), ("failed", "Failed")], db_index=True, default="pending", max_length=16)),
                ("input_snapshot", models.JSONField(blank=True, default=dict)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="extraction_runs", to="cases.case")),
                ("schema", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="extraction_runs", to="intelligence.fieldschema")),
            ],
        ),
        migrations.CreateModel(
            name="ExtractedFact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("value", models.JSONField()),
                ("normalized_value", models.JSONField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(choices=[("proposed", "Proposed"), ("confirmed", "Confirmed"), ("conflicted", "Conflicted"), ("rejected", "Rejected")], db_index=True, default="proposed", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="facts", to="cases.case")),
                ("extraction_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="facts", to="intelligence.extractionrun")),
                ("field", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="facts", to="intelligence.fielddefinition")),
            ],
        ),
        migrations.CreateModel(
            name="FactEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("evidence", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fact_links", to="evidence.evidence")),
                ("fact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence_links", to="intelligence.extractedfact")),
                ("relevance", models.FloatField(blank=True, null=True)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("fact", "evidence"), name="uniq_fact_evidence")],
            },
        ),
        migrations.CreateModel(
            name="CaseFieldIssue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("issue_type", models.CharField(choices=[("missing", "Missing"), ("conflict", "Conflict"), ("invalid", "Invalid")], db_index=True, max_length=16)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("open", "Open"), ("resolved", "Resolved")], db_index=True, default="open", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="field_issues", to="cases.case")),
                ("field", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="issues", to="intelligence.fielddefinition")),
            ],
        ),
    ]
