# Generated by Django 5.1

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evidence", "0001_initial"),
        ("intelligence", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUpQuestion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("question_text", models.TextField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("asked", "Asked"), ("answered", "Answered"), ("cancelled", "Cancelled")], db_index=True, default="pending", max_length=16)),
                ("asked_at", models.DateTimeField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("answer_evidence", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="answered_followups", to="evidence.evidence")),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="follow_up_questions", to="cases.case")),
                ("issue", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="follow_up_question", to="intelligence.casefieldissue")),
            ],
        ),
    ]
