# Generated by Django 5.1

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("ready_for_review", "Ready for review"), ("approved", "Approved")], db_index=True, default="draft", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("case", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="report", to="cases.case")),
            ],
        ),
        migrations.CreateModel(
            name="ReportRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("revision_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("structured_data", models.JSONField(blank=True, default=dict)),
                ("source_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="report_revisions", to=settings.AUTH_USER_MODEL)),
                ("report", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="reports.report")),
            ],
            options={
                "ordering": ["revision_number"],
                "constraints": [models.UniqueConstraint(fields=("report", "revision_number"), name="uniq_report_revision_number")],
            },
        ),
        migrations.AddField(
            model_name="report",
            name="current_revision",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="current_for_reports", to="reports.reportrevision"),
        ),
        migrations.CreateModel(
            name="ReportSection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.SlugField(max_length=96)),
                ("title", models.CharField(max_length=180)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("content", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("revision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="reports.reportrevision")),
            ],
            options={
                "ordering": ["sequence", "key"],
                "constraints": [models.UniqueConstraint(fields=("revision", "key"), name="uniq_revision_section_key")],
            },
        ),
        migrations.CreateModel(
            name="ReportApproval",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                ("approved_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="report_approvals", to=settings.AUTH_USER_MODEL)),
                ("report", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approvals", to="reports.report")),
                ("revision", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="approvals", to="reports.reportrevision")),
            ],
        ),
    ]
