# Generated by Django 5.1 on 2026-09-10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSectionReview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("decision", models.CharField(choices=[("accepted", "Accepted"), ("needs_edit", "Needs edit"), ("rejected", "Rejected")], db_index=True, max_length=24)),
                ("note", models.TextField(blank=True)),
                ("evidence_snapshot", models.JSONField(blank=True, default=list)),
                ("reviewed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="report_section_reviews", to=settings.AUTH_USER_MODEL)),
                ("revision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="section_reviews", to="reports.reportrevision")),
                ("section", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="reports.reportsection")),
            ],
        ),
        migrations.AddConstraint(
            model_name="reportsectionreview",
            constraint=models.UniqueConstraint(fields=("revision", "section", "reviewer"), name="uniq_revision_section_reviewer"),
        ),
    ]
