# Generated by Django 5.1

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseAttachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(max_length=32)),
                ("external_file_id", models.CharField(max_length=255)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=150)),
                ("declared_size", models.BigIntegerField(blank=True, null=True)),
                ("actual_size", models.BigIntegerField(blank=True, null=True)),
                ("provider_file_path", models.TextField(blank=True)),
                ("storage_key", models.CharField(blank=True, max_length=500)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("fetching", "Fetching"), ("stored", "Stored"), ("rejected", "Rejected"), ("failed", "Failed")], db_index=True, default="pending", max_length=16)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="attachment", to="messaging.casemessage")),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("job_type", models.CharField(choices=[("fetch_attachment", "Fetch attachment"), ("transcribe_audio", "Transcribe audio"), ("extract_document", "Extract document"), ("analyze_image", "Analyze image")], max_length=32)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("cancelled", "Cancelled")], db_index=True, default="pending", max_length=16)),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("available_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attachment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jobs", to="processing.caseattachment")),
            ],
            options={
                "indexes": [models.Index(fields=["status", "available_at", "priority"], name="proc_job_queue_idx")],
            },
        ),
        migrations.CreateModel(
            name="ProcessingAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("succeeded", models.BooleanField(default=False)),
                ("error_class", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attempt_records", to="processing.processingjob")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("job", "attempt_number"), name="uniq_job_attempt_number")],
            },
        ),
    ]
